---
title: Data Science Portfolio
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: htaylor2979@gmail.com
description: You have found the portfolio of Hellen Taylor. I am a detail-oriented,
  analytical problem solver with academic experience in data visualization and SQL
  and real-world experience in cleaning retail product data from multiple suppliers.
baseurl: 
url: https://htaylor2979.github.io
# Author Settings
author: Hellen Taylor # add your name
author-img: hellen-taylor-profile-photo.jpg # add your photo
#about-author: I am  # add description
social-github: htaylor2979 # add your Github handle
social-linkedin: htaylor2979 # add your Linkedin handle
social-email: htaylor2979@gmail.com # add your Email address
#github_username: htaylor2979
markdown: kramdown
remote_theme: " artemsheludko/flexible-jekyll "
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-data
- jekyll-remote-theme
- 
exclude:
- drafts
- - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
paginate: 8
paginate_path: "/page/:num"
