---
title: Data Science Portfolio
timezone: America/New_York
email: htaylor2979@gmail.com
description: You have found the portfolio of Hellen Taylor. I am a detail-oriented,
  analytical problem solver with academic experience in data visualization and SQL
  and real-world experience in cleaning retail product data from multiple suppliers.
baseurl: 
url: https://htaylor2979.github.io
github_username: htaylor2979
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
- jekyll-feed
exclude:
- drafts
